title: Aleksandr Hovhannisyan
author: Aleksandr Hovhannisyan
description: >-
  I'm Aleksandr, a software developer who's passionate about solving problems,
  creating beautiful user interfaces, and sharing my knowledge with others. Get in touch!
keywords: [Aleksandr Hovhannisyan]
url: https://aleksandrhovhannisyan.github.io

plugins:
  - jekyll-feed
  - jekyll-sitemap
include: [_pages]

defaults:
  -
    scope:
      path: _pages
      type: pages
    values:
      isPost: false
      layout: default
  -
    scope:
      path: _posts
      type: posts
    values:
      customJS: [blogImage, copyCode]
      isPost: true
      isBlogPage: true
      layout: post
      excerpt: ""
      permalink: /blog/:categories/:title/
  -
    scope:
      path: _posts/dev
    values:
      categories: dev
  -
    scope:
      path: _posts/computer-science
    values:
      categories: computer-science
  -
    scope:
      path: _posts/gaming
    values:
      categories: gaming
  -
    scope:
      path: _posts/music
    values:
      categories: music
  -
    scope:
      path: _posts/writing
    values:
      categories: writing
  -
    scope:
      path: tag
      type: pages
    values:
      isBlogPage: true
      layout: tagPage
      customJS: [blogImage]
      noindex: true
