title: Aleksandr Hovhannisyan
author: Aleksandr Hovhannisyan
description: "I'm a software developer who's passionate about tinkering with code, solving problems, and having fun. Get in touch!"
keywords: [Aleksandr Hovhannisyan, github pages resume, github pages portfolio, github pages personal website]
url: "https://aleksandrhovhannisyan.github.io/"
github_username: AleksandrHovhannisyan

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
include: ['_pages']

defaults:
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:categories/:title/
  -
    scope:
      path: "_posts/programming"
    values:
      categories: [Programming]
  -
    scope:
      path: "_posts/gaming"
    values:
      categories: [Gaming]
  -
    scope:
      path: "_posts/other"
    values:
      categories: [Other]


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
