title: Aleksandr Hovhannisyan
author: Aleksandr Hovhannisyan
description: "Hey there! I'm Aleksandr, a software developer who's passionate about solving problems and having fun. Get in touch!"
keywords: [Aleksandr Hovhannisyan, github pages resume, github pages portfolio, github pages personal website]
url: "https://aleksandrhovhannisyan.github.io/"
github_username: AleksandrHovhannisyan

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
include: ['_pages']

defaults:
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      isPost: false
      layout: "default"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      isPost: true
      layout: "post"
      permalink: /blog/:categories/:title/
  -
    scope:
      path: "_posts/dev"
    values:
      needsCodeFont: true
      categories: [Dev]
  -
    scope:
      path: "_posts/cs101"
    values:
      needsCodeFont: true
      categories: [CS101]
  -
    scope:
      path: "_posts/gaming"
    values:
      categories: [Gaming]
  -
    scope:
      path: "_posts/music"
    values:
      categories: [Music]


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
