title: Aleksandr Hovhannisyan
author: Aleksandr Hovhannisyan
description: >-
  I'm Aleksandr, a software developer who's passionate about solving problems,
  creating beautiful user interfaces, and sharing my knowledge with others. Get in touch!
keywords: [Aleksandr Hovhannisyan]
url: https://aleksandrhovhannisyan.com
issues_repo: AleksandrHovhannisyan/aleksandrhovhannisyan.com
bug_report: https://github.com/AleksandrHovhannisyan/aleksandrhovhannisyan.com/issues/new?assignees=&labels=bug&template=bug_report.md&title=Bug+Report%3A+%5BConcise+Summary+Here%5D

destination: _site
source: src

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  
include:
  - _pages
  - _redirects

exclude:
  - webpack
  - node_modules

sass:
  style: compressed

kramdown:
  math_engine: katex

collections:
  notes:
    output: true
    permalink: /notes/:title/

autopages:
  enabled: true

  categories: 
    # Optional, the list of layouts that should be processed for every category found in the site
    layouts: []

  # Collection pages, omit to disable
  collections:
    layouts: []
  
  # Tag pages, omit to disable
  tags:
    layouts: [tagPage.html]
    title: 'Blog'
    permalink: '/tag/:tag'
    slugify:
      mode: 'default'   # :tag is slugified.
      case: false

pagination:
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 20

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: 'Blog'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

defaults:
  -
    scope:
      path: _pages
      type: pages
    values:
      is_post: false
      layout: default
  -
    scope:
      path: _posts
      type: posts
    values:
      is_post: true
      layout: post
      excerpt: ""
      permalink: /blog/:categories/:title/
      img_path: assets/img/posts
  - 
    scope:
      path: _notes
    values:
      is_post: true
      layout: post
      excerpt: ""
      img_path: assets/img/notes
  -
    scope:
      path: _posts/dev
    values:
      categories: dev
  -
    scope:
      path: _posts/computer-science
    values:
      categories: computer-science
  -
    scope:
      path: _posts/off-topic
    values:
      categories: off-topic
