title: Aleksandr Hovhannisyan
author: Aleksandr Hovhannisyan
description: Hey there! I'm Aleksandr, a software developer who's passionate about solving problems and having fun. Get in touch!
keywords: [Aleksandr Hovhannisyan, github pages resume, github pages portfolio, github pages personal website]
url: https://aleksandrhovhannisyan.github.io/
github_username: AleksandrHovhannisyan

plugins:
  - jekyll-feed
  - jekyll-sitemap
include: [_pages]

defaults:
  -
    scope:
      path: _pages
      type: pages
    values:
      isPost: false
      layout: default
  -
    scope:
      path: _posts
      type: posts
    values:
      customJS: [blogImage]
      isPost: true
      isBlogPage: true
      layout: post
      permalink: /blog/:categories/:title/
  -
    scope:
      path: _posts/dev
    values:
      categories: dev
  -
    scope:
      path: _posts/cs101
    values:
      categories: cs101
  -
    scope:
      path: _posts/gaming
    values:
      categories: gaming
  -
    scope:
      path: _posts/music
    values:
      categories: music
  -
    scope:
      path: tag
      type: pages
    values:
      isBlogPage: true
      layout: tagPage
      customJS: [blogImage]
      noindex: true
